"""Add Artifact fields

Revision ID: 81604a1bec26
Revises: 6587bdc112e4
Create Date: 2026-09-15 02:06:18.986326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '81604a1bec26'
down_revision: Union[str, Sequence[str], None] = '6587bdc112e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artifacts', sa.Column('format', sa.String(length=50), nullable=False))
    op.add_column('artifacts', sa.Column('word_count', sa.Integer(), nullable=True))
    op.add_column('artifacts', sa.Column('sources', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artifacts', 'sources')
    op.drop_column('artifacts', 'word_count')
    op.drop_column('artifacts', 'format')
    # ### end Alembic commands ###
